<?php
$session = $this->_getSession();
if($this->getRequest()->getParam('rfId') || $session->getData('referralId')!=""):


    $refereeDetails = array();
    $referralPersonalDetails = array();
    if($rfCode = $this->setReferralCode()){
        $refereeDetails = $this->getRefereeDetails($rfCode);
        $referralPersonalDetails = $this->getReferralPersonalDetails($refereeDetails['referer_id']);
    }
    ?>
    <?php if($refereeDetails && $referralPersonalDetails): ?>
    <table border="0">
        <tbody>
            <tr>
                <td>Referred By : </td>
                <td><?php echo $referralPersonalDetails['firstname']." ".$referralPersonalDetails['lastname'] ?></td>
            </tr>
            <tr>
                <td>Referral Email : </td>
                <td><?php echo $referralPersonalDetails['email']; ?></td>
            </tr>
        </tbody>
    </table>
        <input type="hidden" name="referral_code" id="referral_code" value="<?php echo $rfCode ?>">
        <br>
    <!--    <script type="text/javascript">-->
    <!--        document.body.onLoad = function() {-->
    <!--            oFormObject = document.forms['form-validate'];-->
    <!--            oFormObject.element['email'].value("111");-->
    <!--        };-->
    <!---->
    <!--    </script>-->
    <?php else: ?>
        <table border="0">
            <tbody>
            <tr>
                <td>Invalid referral code. Referral details not found.</td>
            </tr>
            </tbody>
        </table>
        <br>
    <?php endif; ?>
<?php endif; ?>